### PR TITLE
Add styling and fix overflow of entries in the table of contents

### PR DESCRIPTION
**Pull request by elpoelma**
This PR adds styling to the dummy application and ensures the entries of the table of contents do not overflow.

### CODE REVIEW

**Comment by elpoelma** [comment]
Solves https://binnenland.atlassian.net/browse/GN-3656?atlOrigin=eyJpIjoiM2NkODEwZWRkMTI5NDFlMTlkN2I5MWNiMjhhZWEzNTIiLCJwIjoiaiJ9.

**Comment by lagartoverde** [comment]
Wouldn't it be better to break to a second line instead of the ...?

**Comment by Dietr** [comment]
Added some temporary styling for the button to wrap to the next line. Will add a new property to the button component so we don't need to override the styling here.

**Comment by elpoelma** [comment]
> Added some temporary styling for the button to wrap to the next line. Will add a new property to the button component so we don't need to override the styling here.

Thanks, I wasn't really sure what the best solutions was here in terms of design/ux.

**Pull request merged**
